{{ if .Values.createRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: furan
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - list
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: furan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: furan
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.serviceAccountName }}"
    namespace: "{{ .Release.Namespace }}"
{{ end }}
