{{- if .Values.createServiceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.serviceAccountName }}'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations: 
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end -}}