---
kind: pipeline
name: publish-image
steps:
- name: publish
  image: militarpancho1/drone-plugins-gcr:20.10.8
  privileged: true
  settings:
    mtu: 1460
    json_key:
      from_secret: GCR_TOKEN
    registry: europe-west1-docker.pkg.dev
    repo: europe-west1-docker.pkg.dev/graphext-development/docker/furan2
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: ffa7a24e7c03bfef79981d9759baebd46266d42d40ac40265c3eafc072144f91

...
