---
kind: pipeline
name: publish-image
steps:
- name: publish
  image: militarpancho1/drone-plugins-gcr:20.10.8
  privileged: true
  settings:
    mtu: 1460
    json_key:
      from_secret: GCR_TOKEN
    registry: eu.gcr.io
    repo: europe-west1-docker.pkg.dev/graphext-development/docker/furan2
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: eeeb684f8e3fbe9786f65e372ff6248726a238b0b8d4aba7ac542ddba93ab281

...
