---
kind: pipeline
name: publish-image
steps:
- name: publish
  image: militarpancho1/drone-plugins-gcr:20.10.8
  privileged: true
  settings:
    mtu: 1460
    json_key:
      from_secret: GCR_TOKEN
    registry: eu.gcr.io
    repo: eu.gcr.io/graphext-development/furan2
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: 170d6fe644f9bb68bac8f631cc0bfca9eaedbf9ca160cc35674a626f81604e15

...
