// Code generated by "stringer -type=BuildStatus"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BuildStatusUnknown-0]
	_ = x[BuildStatusNotStarted-1]
	_ = x[BuildStatusBuilding-2]
	_ = x[BuildStatusPushing-3]
	_ = x[BuildStatusSuccess-4]
	_ = x[BuildStatusBuildFailure-5]
	_ = x[BuildStatusPushFailure-6]
	_ = x[BuildStatusNotNeeded-7]
}

const _BuildStatus_name = "BuildStatusUnknownBuildStatusNotStartedBuildStatusBuildingBuildStatusPushingBuildStatusSuccessBuildStatusBuildFailureBuildStatusPushFailureBuildStatusNotNeeded"

var _BuildStatus_index = [...]uint8{0, 18, 39, 58, 76, 94, 117, 139, 159}

func (i BuildStatus) String() string {
	if i < 0 || i >= BuildStatus(len(_BuildStatus_index)-1) {
		return "BuildStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuildStatus_name[_BuildStatus_index[i]:_BuildStatus_index[i+1]]
}
