// Code generated by "stringer -type=BuildCacheType"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownCacheType-0]
	_ = x[DisabledCacheType-1]
	_ = x[InlineCacheType-2]
	_ = x[S3CacheType-3]
}

const _BuildCacheType_name = "UnknownCacheTypeDisabledCacheTypeInlineCacheTypeS3CacheType"

var _BuildCacheType_index = [...]uint8{0, 16, 33, 48, 59}

func (i BuildCacheType) String() string {
	if i < 0 || i >= BuildCacheType(len(_BuildCacheType_index)-1) {
		return "BuildCacheType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuildCacheType_name[_BuildCacheType_index[i]:_BuildCacheType_index[i+1]]
}
