{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minio.serviceAccountName" . }}
  labels:
    app: minio
    chart: minio-8.0.10
    release: {{ .Release.Name }}
    heritage: Helm
{{- end -}}